default: &default
  adapter: postgresql
  host: localhost

development:
  database: amazon_cognito_demo_development
  <<: *default

test:
  database: amazon_cognito_demo_test
  <<: *default

staging:
  database: amazon_cognito_demo_staging
  <<: *default

production:
  database: amazon_cognito_demo_production
  <<: *default
